## Players And Their Attributes

In [1]:
# Import packages
import pandas as pd
from datetime import date

In [2]:
# load csv file
df_pla_attr = pd.read_csv('data/Player_Attributes.csv')
df_pla = pd.read_csv('data/Player.csv')

In [3]:
# Sort date by descending to have recent entry at the top
df_pla_attr.sort_values(by='date', ascending = False)

# Remove duplicates whiles keeping the recent entry of player's attribute
df_pla_attr.drop_duplicates(subset='player_fifa_api_id', inplace=True)

In [4]:
# Drop rows with null values
df_pla_attr.dropna(inplace = True)

In [5]:
ratings = ['medium', 'high', 'low']

# Remove ratings other than 'medium', 'high' and 'low'
df_pla_attr = df_pla_attr[df_pla_attr['attacking_work_rate'].isin(ratings)]
df_pla_attr = df_pla_attr[df_pla_attr['defensive_work_rate'].isin(ratings)]

In [6]:
# Print the number of samples and columns in the dataset
print('The number of players in the dataset is', df_pla_attr.shape[0], 
     '\nand the number of columns is', df_pla_attr.shape[1])

The number of players in the dataset is 9907
and the number of columns is 42

In [7]:
# merge two datasets, Player and Player_attributes
df_players = pd.merge(df_pla, df_pla_attr, on='player_api_id')

In [8]:
# Drop columns 
columns = ['id_x', 'id_y', 'player_fifa_api_id_y', 'date','crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy', 'long_passing', 
       'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 
       'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']

df_players.drop(columns=columns, inplace=True)

In [9]:
# Calculate Age from birthday
today = date.today()

df_players['birthday'] = pd.to_datetime(df_players['birthday']).dt.date
df_players['Age'] = today - df_players['birthday']
df_players['Age'] = df_players['Age'].dt.days.astype("int16") // 365

In [10]:
# Calculate the BMI
#convert weight pounds to kg
wei_kg = df_players['weight'] * 0.45359237

df_players['BMI'] = round((wei_kg / df_players['height'] / df_players['height']) * 10000, 2)

In [11]:
df_players.head()

,player_api_id,player_name,player_fifa_api_id_x,birthday,height,weight,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,ball_control,Age,BMI
0,505942,Aaron Appindangoye,218353,1992-02-29,182.88,187,67.0,71.0,right,medium,medium,49.0,32,25.36
1,155782,Aaron Cresswell,189615,1989-12-15,170.18,146,74.0,76.0,left,high,medium,71.0,34,22.87
2,162549,Aaron Doran,186170,1991-05-13,170.18,163,65.0,67.0,right,medium,medium,67.0,33,25.53
3,30572,Aaron Galindo,140161,1982-05-08,182.88,198,69.0,69.0,right,medium,medium,62.0,42,26.85
4,23780,Aaron Hughes,17725,1979-11-08,182.88,154,70.0,70.0,right,medium,medium,58.0,44,20.89

In [12]:
df_players.describe()

,player_api_id,player_fifa_api_id_x,height,weight,overall_rating,potential,ball_control,Age,BMI
count,9907.000000,9907.000000,9907.000000,9907.000000,9907.000000,9907.000000,9907.000000,9907.000000,9907.000000
mean,166369.941052,170832.715757,181.908816,168.398607,68.274150,71.017967,62.377915,36.406278,23.057986
std,164424.792893,54555.569210,6.396656,15.077540,6.282159,6.225171,15.491598,5.110743,1.328869
min,2625.000000,2.000000,157.480000,117.000000,47.000000,49.000000,9.000000,25.000000,17.870000
25%,37260.500000,158675.500000,177.800000,159.000000,64.000000,67.000000,58.000000,32.500000,22.160000
50%,110145.000000,187931.000000,182.880000,168.000000,68.000000,71.000000,66.000000,36.000000,23.060000
75%,239961.500000,205068.500000,185.420000,179.000000,73.000000,75.000000,72.000000,40.000000,23.870000
max,750584.000000,234141.000000,208.280000,243.000000,94.000000,94.000000,96.000000,55.000000,30.870000

In [13]:
# data only on RIGHT preferred foot
df_players[df_players['preferred_foot'] == 'right'].describe()

,player_api_id,player_fifa_api_id_x,height,weight,overall_rating,potential,ball_control,Age,BMI
count,7481.000000,7481.000000,7481.000000,7481.000000,7481.000000,7481.000000,7481.000000,7481.000000,7481.000000
mean,165463.037161,170580.981152,182.156129,168.968587,68.264804,70.995188,61.712873,36.453950,23.073493
std,164719.072444,54832.238971,6.430606,15.112951,6.337209,6.224969,16.079038,5.144209,1.329496
min,2625.000000,6.000000,157.480000,117.000000,47.000000,49.000000,9.000000,25.000000,17.870000
25%,37025.000000,158219.000000,177.800000,159.000000,64.000000,66.000000,58.000000,33.000000,22.160000
50%,109088.000000,187334.000000,182.880000,168.000000,68.000000,71.000000,65.000000,36.000000,23.060000
75%,237610.000000,205114.000000,187.960000,179.000000,73.000000,75.000000,72.000000,40.000000,23.870000
max,750584.000000,234141.000000,208.280000,243.000000,93.000000,94.000000,93.000000,55.000000,30.870000

In [14]:
# data only on LEFT preferred foot
df_players[df_players['preferred_foot'] == 'left'].describe()

,player_api_id,player_fifa_api_id_x,height,weight,overall_rating,potential,ball_control,Age,BMI
count,2426.000000,2426.000000,2426.000000,2426.000000,2426.000000,2426.000000,2426.000000,2426.000000,2426.000000
mean,169166.539571,171608.983924,181.146183,166.640973,68.302968,71.088211,64.428689,36.259275,23.010169
std,163516.147778,53697.186333,6.230593,14.833596,6.110472,6.226552,13.315833,5.004325,1.326064
min,2768.000000,2.000000,160.020000,121.000000,48.000000,51.000000,12.000000,25.000000,18.410000
25%,37809.000000,162301.250000,177.800000,157.000000,64.000000,67.000000,60.000000,32.000000,22.150000
50%,114217.000000,188708.000000,180.340000,165.000000,68.000000,71.000000,67.000000,36.000000,23.060000
75%,243249.500000,204822.250000,185.420000,176.000000,73.000000,75.000000,73.000000,40.000000,23.870000
max,744907.000000,233911.000000,203.200000,225.000000,94.000000,94.000000,96.000000,53.000000,29.570000

In [15]:
df_players.to_excel('data/Players_and_thier_Attributes.xlsx', sheet_name='Players', index=False)